### ISSUE TITLE
Support OSX 10.x pls?

### ISSUE THREAD

**Issue by evandrix** [petergeoghegan/gensort#1]

**Comment by petergeoghegan** [comment]
@evandrix I don't use OSX. The locale support that Postgres uses for OSX is known to be very slow, so that doesn't seem particularly compelling.

**Comment by hansenc** [comment]
For anyone else looking for an OS X build of gensort, you can find it [here](https://github.com/scslab/bad/tree/master/gensort) from a Stanford Secure Computer Systems Lab repo.

(Note: you can check out only the sub-folder using SVN with this command `svn co https://github.com/scslab/bad/trunk/gensort` since GitHub supports this).
